name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: false
      # 生成静态文件
    - name: Build
      run: yarn && yarn docs:build
          # 生成静态文件
    - name: Deploy
      # 引用别人的部署插件
      uses: JamesIves/github-pages-deploy-action@releases/v3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # TARGET_REPO: cangxiaocoder/docs
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/
        COMMIT_MESSAGE: 笔记、博客
        # CNAME: https://www.xxx.com